name: test-desktop

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-desktop:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: test-desktop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: powershell
        run: ./1.build.ps1 test
