name: test-core

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-core:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: test-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: ./1.build.ps1 test
